version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "...Installing your dependencies..."
      - npm install
      - echo "...Installing SonarScanner..."
      - npm install -g sonarqube-scanner

  pre_build:
    commands:
      - echo "...Running tests and generating coverage report..."
      - npm test

  build:
    commands:
      - echo "...Building your react app..."
      - npm run build

  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - sonar-scanner -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.token=$SONAR_TOKEN -Dsonar.projectKey=$SONAR_PROJECT_KEY

artifacts:
  files:
    - '**/*'
  base-directory: dist
